version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/project/home

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/project
    paths:
      - home

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install Dependencies
          command: npm ci
      - *persist_to_workspace

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run check-lint

  type:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run type

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm test

  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: NODE_ENV=production npm run build
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - type:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
