version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9@sha256:c092b9cc8eb01d578ac5f7f90b7c9dec5638cc6ce35f3d959764409f9aaa8233

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn greenkeeper-lockfile-update
      - run: yarn type
      - run: yarn test
      - run: yarn build
      - run: yarn greenkeeper-lockfile-upload

